backend: "python"
input [
  {
    name: "speakers"
    data_type: TYPE_INT64
    dims: [ 1 ]
  },
  {
    name: "texts"
    data_type: TYPE_INT64
    dims: [ 1, -1 ]
  },
  {
    name: "text_lens"
    data_type: TYPE_INT64
    dims: [ 1 ]
  },
  {
    name: "max_text_lens"
    data_type: TYPE_INT64
    dims: [1]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1, -1, -1 ]
  },
  {
    name: "postnet_output"
    data_type: TYPE_FP32
    dims: [ 1, -1, -1 ]
  },
  {
    name: "p_predictions"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  },
  {
    name: "e_predictions"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  },
  {
    name: "log_d_predictions"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  },
  {
    name: "d_rounded"
    data_type: TYPE_FP32
    dims: [ 1, -1 ]
  },
  {
    name: "src_masks"
    data_type: TYPE_BOOL
    dims: [ 1, -1 ]
  },
  {
    name: "mel_masks"
    data_type: TYPE_BOOL
    dims: [ 1, -1 ]
  },
  {
    name: "src_lens"
    data_type: TYPE_INT64
    dims: [ 1 ]
  },
  {
    name: "mel_lens"
    data_type: TYPE_INT64
    dims: [ 1 ]
  }
]
